# Generated by Django 4.2.27 on 2026-01-17 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ig_media_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ig_url', models.TextField()),
                ('song_title', models.CharField(blank=True, default='', max_length=500)),
                ('artist_name', models.CharField(blank=True, default='', max_length=500)),
                ('album_artwork', models.TextField(blank=True, default='')),
                ('spotify_link', models.TextField(blank=True, default='')),
                ('apple_music_link', models.TextField(blank=True, default='')),
                ('shazam_track_id', models.CharField(blank=True, default='', max_length=100)),
                ('shazam_url', models.TextField(blank=True, default='')),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Song Search',
                'verbose_name_plural': 'Song Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='songs.songsearch')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
            },
        ),
    ]
